### ISSUE TITLE
Support for returning custom message

### ISSUE THREAD

**Issue by vamsden** [alanhamlett/readtime#3]
Hi I think it would be nice if it would allow to add custom message instead of returning the default one.
Like when I do readtime on a particular text it returns like "5 min read", it would be good if I can pass a custom message instead or something like "5 minutes read" in full instead.

**Comment by alanhamlett** [comment]
That's just the default string representation of the returned readtime result, but you can use `result.seconds` to build custom text:

https://github.com/alanhamlett/readtime#usage
